version: "3"
services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
  app-image-process:
    build:
      context: ./image_process
      dockerfile: Dockerfile
    env_file: 
      - ./image_process/.env
    ports:
      - "3002:3002"
    restart: unless-stopped
    depends_on: 
      - app-core
    networks:
      - backend
  app-core:
    build:
      context: ./core
      dockerfile: Dockerfile
    env_file:
      - ./core/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on: 
      - database
      - rabbitmq
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  pg_data:
    driver: local
  rabbit_data:
    driver: local